#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service
PROCESS_NAME="nextcloud"

check_service_initialized init 20-php-fpm

transform_file_var \
                        ADMIN_PASS \
                        ADMIN_USER \
                        DB_HOST \
                        DB_NAME \
                        DB_PASS \
                        DB_PORT \
                        DB_USER \
                        MONITORING_APPLICATION_TOKEN
check_databases
bootstrap_webroot
configure_data_directories
configure_logging
if var_true "${CONTAINER_ENABLE_FIREWALL}" && var_true "${CONTAINER_ENABLE_FAIL2BAN}" ; then configure_fail2ban_nextcloud; fi
install_nextcloud
create_configuration
configure_application_settings
custom_files "${CONTAINER_CUSTOM_PATH}" "${NGINX_WEBROOT}" "${NGINX_USER}" "${NGINX_GROUP}"
custom_scripts

print_info "Nextcloud Version ${NEXTCLOUD_VERSION} ready to be accessed!"
liftoff
