#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service both single

PROCESS_NAME="fail2ban"
check_container_initialized
check_service_initialized init
liftoff

print_debug "Sleeping for 180 seconds before starting Fail2ban to make sure logs are popualated"
sleep 180

print_info "Starting Fail2ban"
if [ "$FAIL2BAN_LOG_TYPE" = "FILE" ] ; then
    silent fail2ban-server -f
else
    fail2ban-server -f
fi
